name: Build docker images (scheduled)

on:
  push:
    branches:
      - test_fix_doc_builder_docker_image_build

concurrency:
  group: docker-images-builds
  cancel-in-progress: false

jobs:
  doc-builder:
    name: "Doc builder"
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Check out code
        uses: actions/checkout@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./docker/transformers-doc-builder
          push: false
          tags: huggingface/transformers-doc-builder-no-push
